# Generated by Django 5.2 on 2026-08-09 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'สำเร็จ'), ('fail', 'ล้มเหลว'), ('partial', 'บางส่วน')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('records_saved', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Log การดึงข้อมูล',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='LotteryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField(unique=True, verbose_name='วันที่ออกรางวัล')),
                ('first_prize', models.CharField(blank=True, max_length=20, verbose_name='รางวัลที่ 1')),
                ('two_digit', models.CharField(blank=True, max_length=10, verbose_name='2 ตัวท้าย')),
                ('three_digit', models.CharField(blank=True, max_length=10, verbose_name='3 ตัวท้าย')),
                ('raw_data', models.TextField(blank=True, verbose_name='ข้อมูลดิบ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ผลหวยลาวพัฒนา',
                'verbose_name_plural': 'ผลหวยลาวพัฒนาทั้งหมด',
                'ordering': ['-draw_date'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(verbose_name='งวดที่ทำนาย')),
                ('predicted_first', models.CharField(max_length=20, verbose_name='ทำนายรางวัลที่ 1')),
                ('predicted_two', models.CharField(blank=True, max_length=10, verbose_name='ทำนาย 2 ตัวท้าย')),
                ('predicted_three', models.CharField(blank=True, max_length=10, verbose_name='ทำนาย 3 ตัวท้าย')),
                ('confidence', models.FloatField(default=0.0, verbose_name='ความมั่นใจ (%)')),
                ('model_used', models.CharField(default='ensemble', max_length=50, verbose_name='โมเดลที่ใช้')),
                ('is_correct_two', models.BooleanField(blank=True, null=True, verbose_name='ถูก 2 ตัวท้าย')),
                ('is_correct_three', models.BooleanField(blank=True, null=True, verbose_name='ถูก 3 ตัวท้าย')),
                ('is_correct_first', models.BooleanField(blank=True, null=True, verbose_name='ถูกรางวัลที่ 1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actual_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='lottery.lotteryresult', verbose_name='ผลจริง')),
            ],
            options={
                'verbose_name': 'การทำนาย',
                'verbose_name_plural': 'ประวัติการทำนาย',
                'ordering': ['-target_date'],
            },
        ),
    ]
