# Generated by Django 6.1 on 2026-08-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_prediction_key_digit_prediction_secondary_digit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteryresult',
            name='four_digit',
            field=models.CharField(blank=True, max_length=10, verbose_name='4 ตัวท้าย'),
        ),
        migrations.AddField(
            model_name='lotteryresult',
            name='two_digit_top',
            field=models.CharField(blank=True, max_length=10, verbose_name='2 ตัวบน'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='is_correct_four',
            field=models.BooleanField(blank=True, null=True, verbose_name='ถูก 4 ตัวท้าย'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='is_correct_two_top',
            field=models.BooleanField(blank=True, null=True, verbose_name='ถูก 2 ตัวบน'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='predicted_four',
            field=models.CharField(blank=True, max_length=100, verbose_name='ทำนาย 4 ตัวท้าย'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='predicted_two_top',
            field=models.CharField(blank=True, max_length=100, verbose_name='ทำนาย 2 ตัวบน'),
        ),
    ]
